name: CD-pipeline

on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: 'CI Run ID to pull artifacts from'
        required: false
        type: string

  workflow_run:
    workflows: ["CI-Pipeline"]
    types:
      - completed

env:
  TF_HOME: infra/terraform

jobs:
  CD:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set EFFECTIVE_RUN_ID (workflow_dispatch or workflow_run fallback)
        id: set-run-id
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "run_id=${{ github.event.inputs.ci_run_id }}" >> "$GITHUB_OUTPUT"
          else
            echo "run_id=${{ github.event.workflow_run.id }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Download Terraform Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: terraform
          path: ${{ env.TF_HOME }}
          run-id: ${{ steps.set-run-id.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List downloaded Terraform files
        run: ls -R ${{ env.TF_HOME }}

      - name: Terraform Init
        working-directory: ${{ env.TF_HOME }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_HOME }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_HOME }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.TF_HOME }}
        run: terraform apply -auto-approve
