name: CD-pipeline

on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: 'Run ID of the CI pipeline used to find the artifacts'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    uses: common   # for access to ${{ secrets.TF_API_TOKEN }}
    env:
      TF_HOME: terraform
    steps:
      - name: Download the Terraform Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: terraform
          path: ${{ env.TF_HOME }}
          run-id: ${{ github.event.inputs.ci_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Terraform Artifact Contents
        run: ls ${{ env.TF_HOME }}


      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


      - name: Run Terraform
        run: |
          cd ${{ env.TF_HOME }}
          terraform init
          terraform workspace select pygoat-test
          terraform apply -auto-approve
          cd -
          

          
  prod:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: |
          echo 'Hello world!'
