name: CI-Pipeline

on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  sast-scan:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
  docker-build:
    runs-on: ubuntu-latest
    environment: common
    env:
     DOCKER_USER: ${{ vars.DOCKER_USER }}
     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        uses: docker/login-action@v3.4.0
        with:
      
          # registry: YOUR_REGISTRY
          # Currently uses docker hub, here no information registry is needed.
          # Username used to log against the Docker registry
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{github.run_id}}

      - name: Scan image with docker scout
        uses: docker/scout-action@v1
        with:
          command: cves, recommendations
          image: ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{github.run_id}}
          only-severities: critical,high
          sarif-file: docker-scout-sarif.output.json
          summary: true

          # fail the run if vunrabilites is found
          exit-code: true 

      - name: Upload docker scout with SARIF result
        if: ${{ always() }} 
        # run this even docker scout is resulteda failed
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: docker-scout-sarif.output.json

      
